### ISSUE TITLE
Change `enableReproducibleBuilds` to `disableReproducibleBuilds`.

### ISSUE THREAD

**Issue by coollog** [google/jib#200]
`disableReproducibleBuilds` makes more sense since reproducibility is enabled by default.

**Comment by coollog** [comment]
This should probably be changed to just `reproducible` to match `jib-gradle-plugin`. #212

**Comment by loosebazooka** [comment]
Do we need to make this explicit that it's the layers that are reproducible?

**Comment by coollog** [comment]
Or we could use an explicit version of the distroless image and just update that version as we release new versions?

**Comment by coollog** [comment]
Closing, to be addressed via https://github.com/google/jib/pull/224
