### ISSUE TITLE
Provide easy way to configure additional JVM flags when running the image.

### ISSUE THREAD

**Issue by coollog** [google/jib#201]
Currently, JVM flags can be set on the container entrypoint via the `jvmFlags` configuration option (for `jib-maven-plugin`). However, users may want to run a single built image on multiple places with different JVM flags. The current way of achieving this is to override the entire container entrypoint, which requires knowing the main class.

~~The proposed solution is to define an environment variable (like `JVM_FLAGS`), which gets added as part of the entrypoint invocation for the container. This environment variable can then be set to whatever additional flags (or none) when running the image. This makes it so that the entrypoint does not have to change.~~

~~For example, the entrypoint could look like:~~

~~`java -flagDefinedInBuild $JVM_FLAGS my.main.Class`~~

~~Implementation suggestions:~~
~~- `EntrypointBuilder` builds the entrypoint~~
~~- integration test for application that uses JVM flags~~

**Comment by coollog** [comment]
@loosebazooka @patflynn @TadCordle As discussed, how does this sound?

**Comment by patflynn** [comment]
+1.

**Comment by TadCordle** [comment]
Sure, I'll take a look.

**Comment by coollog** [comment]
Closing as [$JAVA_TOOLS_OPTIONS is the environment variable that is used by the JVM](https://stackoverflow.com/questions/12577437/how-to-set-a-java-system-property-so-that-it-is-effective-whenever-i-start-jvm-w) to do exactly this.
