### ISSUE TITLE
Add more suggestions for various build failures.

### ISSUE THREAD

**Issue by coollog** [google/jib#27]
When running `mvn jib:build`, there are various failures caught in the `BuildImageMojo#buildImage` method. These catches provide extra feedback to the user to help them understand the issue and provide suggestions for how to fix the issue.

The actionables are to:

1. Figure out what other build failures there are, if any (compile a list and maybe add that below)
2. Add similar handling for these build failures.
3. (Maybe improve how these failures are handled currently)

Build failures to handle:
- [ ] ~~Could not find or load main class~~ Just noticed #189 is already a thing
- [x] "Unknown host" when registry is misconfigured
- [x] "Obtaining project build output files failed" when project hasn't been compiled yet (e.g. running `mvn clean jib:build`)
- [x] "Unable to parse configuration of mojo: Cannot convert `x` to Enum" if imageFormat isn't `Docker` or `OCI`
- [ ] Unrecognized JVM flag (See #192)

**Comment by coollog** [comment]
Another thing I saw was if for example, the user does not define a credHelper, but Jib tried to use the Docker config for credentials, but the credentials in there were for a different GCP project than the project you want to push to, the build fails with no suggestions. We might want to explore providing better feedback in these cases where we have the same registry but the credentials retrieved are not correct.

**Comment by TadCordle** [comment]
I haven't been able to reproduce that one yet, but I opened an issue for it - #196
