### ISSUE TITLE
Ensure reproducibility of images.

### ISSUE THREAD

**Issue by coollog** [google/jib#7]
From https://github.com/GoogleCloudPlatform/minikube-build-tools-for-java/issues/61

Building from the same source files should produce the same image on different computers. This means erasing timestamps (and other variations such as user ids) from files.

**Comment by loosebazooka** [comment]
The current plan for this is :
- sort entries by name
- set `mtime = 0`
- set `userId = 0`
- set `groupId = 0`
- set `userName = ""`
- set `groupName = ""`

**Comment by coollog** [comment]
Sounds great!
