### ISSUE TITLE
Warn the user if a Docker credential helper could not be found.

### ISSUE THREAD

**Issue by coollog** [google/jib#82]
Since we are inferring Docker credential helpers, we should not fail the build if one is not found, but rather just provide a warning.

**Comment by patflynn** [comment]
if we detect that there are no credentials available using either cred
helpers or manual configuration do we fail immediately? I get the sense
that this doesn't fail until after the build but it probably should.

**Comment by coollog** [comment]
We don't fail immediately, but fail if we encounter an `Unauthorized` error from a registry. The reason is that pulls from public registries will not require credentials, and pushes to local registries will likely not require credentials either.
